name: Build and Deploy Flutter Web

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: ~/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # or your local version
          cache: true

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            gym_buddy/.dart_tool
            gym_buddy/build
          key: ${{ runner.os }}-pub-${{ hashFiles('gym_buddy/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Get Flutter dependencies
        working-directory: gym_buddy
        run: flutter pub get

      - name: Build Flutter web release
        working-directory: gym_buddy
        run: flutter build web --release --base-href "/gymbuddies-fitnesstrackerapp/"

      - name: Deploy to web-hosted branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: web-hosted
          folder: gym_buddy/build/web
          clean: true
